### ISSUE TITLE
Bridge Domain can not created

### ISSUE THREAD

**Issue by leeyome** [carlniger/acitool#22]
Hi.

I used this tool with new ACI set deployment.
It's well worked, but when I try to create BD, Error displayed.

********************************************************************************
Starting work on Fabric Pod Policies section
********************************************************************************
********************************************************************************
Starting work on Fabric Access Policies section
********************************************************************************
********************************************************************************
Starting work on Tenant Configuration section
********************************************************************************
Deploying line 38 from section Tenant Configuration...
Error 400 - Bad Request - ABORT!
Probably have a bad URL or payload
********************************************************************************

![image](https://user-images.githubusercontent.com/20239160/33975306-0194a290-e0d1-11e7-8c38-886e6fc73561.png)

Can you help me?

Thanks.

**Comment by carlmontanari** [comment]
Can you check to make sure there are no trailing spaces in any of the text fields... this has been a problem recently and am hoping to fix when I get some time (easy fix). Also make sure that the tenant you're trying to put that BD into exists. Let me know if that helps and we can take it from there.
Carl

**Comment by leeyome** [comment]
There is no space I checked.
Is there any other check method?
and one more problem.
switch profile was created correctly, but although I filled in status with 'deleted', it was created too.

**Comment by carlmontanari** [comment]
I will try to test the deleted thing tomorrow. Best way to check whats up on the BD is to print out the status code returned from the APIC. Add the following just after line 61 in acipdt.py:

print(r.text)

That will print out what APIC is telling us and we can go from there.

Carl

**Comment by leeyome** [comment]
I tried to fill status in 'created,modified', then BD was created.
and I added that code in acipdt.py & tested with 'created', but I can't find any additional message.
only this message. 

```
Error 400 - Bad Request - ABORT!
Probably have a bad URL or payload
```

**Comment by carlmontanari** [comment]
Can you please attach the spreadsheet (at least the full BD section) so I can test this weekend please?

Carl

**Comment by leeyome** [comment]
Sorry for late.

Here it is.


[ACI Deploy.zip](https://github.com/carlniger/acitool/files/1566824/ACI.Deploy.zip)

**Comment by carlmontanari** [comment]
Ah I see whats going on here. So normally for the "status" -- I always just use "created, modified" because I'm lazy... since you're using created (which is arguably a smarter thing to do!), it is attempting to "create" a relationship to the VRF... which it is failing on with the following message:

{"totalCount":"1","imdata":[{"error":{"attributes":{"code":"103","text":"Cannot create Private Network (fvRsCtx); object uni\/tn-TENANT_YM\/BD-BD_YM_INT01\/rsctx already exists."}}}]}

So its trying to "modify" the "rsctx" (relationship to context (VRF)) and is failing because it "already exists"... It doesn't exist but I guess the way I have the jinja/json on the back it gets upset with that.

I think this would be a fairly simple "fix" so I'm going to leave the issue open and mark it as an enhancement and hopefully get it sorted out this week. I'm planning on renaming the repo to acipdt which is what it should have been called in the first place but I'm a noob, after that I will try to fix this.

Carl

**Comment by carlmontanari** [comment]
Ok, just merged in a tweak for this... its not perfect but it works :)

Basically I changed the BD section to no longer specify a VRF, now that is in its own "bd_vrf" section. That section has a hard coded status to "created, modified" because even if you never specify a VRF for your BD the fabric will automagically hook it to common/default. So we basically can't use "created"  there. The downside is there is no "deleted" option now, however the equivalent to that would be to set the VRF to "common/default" which should achieve the same outcome.

Going to close this now. Feel free to open others for the Leaf Profile issue or whatever else you've got going on!

Carl
